# Generated by Django 4.0 on 2021-12-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myfiles', '0005_comment_tur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('fam', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('jins', models.CharField(max_length=10)),
                ('yosh', models.CharField(max_length=10)),
                ('shaxar', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sotib_olingan_maxsulotlar',
            name='ism',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sotib_olingan_maxsulotlar',
            name='tel',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
