# Generated by Django 4.0 on 2021-12-22 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Myfiles', '0006_anketa_sotib_olingan_maxsulotlar_ism_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sotib_olingan_maxsulotlar',
            name='vaqt',
            field=models.TimeField(auto_now=datetime.datetime(2021, 12, 22, 6, 50, 54, 592790, tzinfo=utc)),
            preserve_default=datetime.datetime(2021, 12, 22, 6, 50, 54, 592790, tzinfo=utc),
        ),
    ]
