# Generated by Django 4.0 on 2021-12-23 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Myfiles', '0008_alter_sotib_olingan_maxsulotlar_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotib_olingan_maxsulotlar',
            name='vaqt',
            field=models.TimeField(auto_now=datetime.datetime(2021, 12, 23, 18, 10, 11, 35760, tzinfo=utc)),
        ),
    ]
