# Generated by Django 4.0 on 2021-12-25 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Myfiles', '0009_alter_sotib_olingan_maxsulotlar_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotib_olingan_maxsulotlar',
            name='vaqt',
            field=models.TimeField(auto_now=datetime.datetime(2021, 12, 25, 7, 18, 39, 937772, tzinfo=utc)),
        ),
    ]
